services:
  portfolio:
    build: .
    container_name: yudi-portfolio-web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    volumes:
      - ./src/content:/app/src/content
      - ./public/images:/app/public/images
    networks:
      - server_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`itsdvvn.my.id`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=4321"

networks:
  server_web:
    external: true
