FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=4321

COPY package*.json ./
RUN npm install

COPY dist ./dist
COPY keystatic.config.ts ./keystatic.config.ts

EXPOSE 4321

CMD ["node", "./dist/server/entry.mjs"]
